<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableMsixTooling>true</EnableMsixTooling>
    <SelfContained>true</SelfContained>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsPackageType>None</WindowsPackageType>
    <UseWindowsForms>true</UseWindowsForms>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.2-Experimental9" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
  </ItemGroup>
</Project>
